data:
  input: D:\\idkROM\\idkROM\\data\\dataset_entrada.csv
  output: D:\\idkROM\\idkROM\\data\\dataset_salida.csv

preprocess:
  read mode: pre
  scaler: MinMaxScaler
  validation: single | cross
  test_size: 0.15

model:
  type: neural_network
  hyperparams:
    mode: default
    params:
      n_iter: 10 # only if mode: best
      cv: 5 # only if mode: best

      n_layers: 2 | 3 | 4
      n_neurons: 20 | 50 | 100
      activation: Tanh | ReLU | Sigmoid
      optimizer: Adam | SGD
      learning_rate: 0.001 | 0.01 | 0.1
      #loss: [mse, mae, mape]
      #metrics: [mae, mse, mape]
      epochs: 500 | 1000 | 3000

#  type: gaussian_process
#  hyperparams:
#    mode: manual
#    params:
#      n_iter: 10 # only if mode: best
#      cv: 5 # only if mode: best
#
#      kernel: RBF 
#      noise: 0.0001
#      optimizer: fmin_l_bfgs_b
#      #loss: [mse, mae, mape]
#      #metrics: [mae, mse, mape]


#  type: rbf
#  hyperparams:
#    mode: manual
#    params:
#      n_iter: 10 # only if mode: best
#      cv: 5 # only if mode: best
#
#      gamma: 1.0 
#      #loss: [mse, mae, mape]
#      #metrics: [mae, mse, mape]


#  type: response_surface
#  hyperparams:
#    mode: manual
#    params:
#      n_iter: 10 # only if mode: best
#      cv: 5 # only if mode: best
#
#      degree: 2 
#      #loss: [mse, mae, mape]
#      #metrics: [mae, mse, mape]


#  type: svr
#  hyperparams:
#    mode: manual
#    params:
#      n_iter: 10 # only if mode: best
#      cv: 5 # only if mode: best
#
#      kernel: rbf 
#      C: 1.0
#      epsilon: 0.1
#      #loss: [mse, mae, mape]
#      #metrics: [mae, mse, mape]


evaluate:
  metrics: mae | mse | mape
  plot: True | False
  save: True | False