idk_params:
  n_capas: [model,hyperparams,params,n_layers]
  n_neuronas: [model,hypeparmas, params, n_neurons]

data:
  input: D:\\idkROM\\idkROM\\data\\main_platoHydr_idkFEM_DOE_Results copy_inputs.csv
  output: D:\\idkROM\\idkROM\\data\\main_platoHydr_idkFEM_DOE_Results copy_outputs.csv

preprocess:
  read mode: raw
  scaler: MinMaxScaler
  validation: single | cross
  test_size: 0.15
  validation_size: 

model:
#  type: neural_network
#  hyperparams:
#    mode: manual
#    params:
#      n_iter: 10 # only if mode: best
#      cv: 5 # only if mode: best
#
#      n_layers: 4
#      n_neurons: 5
#      activation: Tanh
#      optimizer: Adam
#      learning_rate: 0.01
#      #loss: [mse, mae, mape]
#      epochs: 1000

#  type: gaussian_process
#  hyperparams:
#    mode: manual
#    params:
#      n_iter: 10 # only if mode: best
#      cv: 5 # only if mode: best
#
#      kernel: RBF 
#      noise: 0.0001
#      optimizer: fmin_l_bfgs_b
#      #loss: [mse, mae, mape]


  type: rbf
  hyperparams:
    mode: manual
    params:
      n_iter: 10 # only if mode: best
      cv: 5 # only if mode: best

      gamma: 1.0 
      #loss: [mse, mae, mape]
      #metrics: [mae, mse, mape]


#  type: response_surface
#  hyperparams:
#    mode: manual
#    params:
#      n_iter: 10 # only if mode: best
#      cv: 5 # only if mode: best
#
#      degree: 2 
#      #loss: [mse, mae, mape]


#  type: svr
#  hyperparams:
#    mode: manual
#    params:
#      n_iter: 10 # only if mode: best
#      cv: 5 # only if mode: best
#
#      kernel: rbf 
#      C: 1.0
#      epsilon: 0.1
#      #loss: [mse, mae, mape]


evaluate:
  metrics: mse
  plot: True 
  save: True