site_name: idkROM Documentation
nav:
  - Home: index.md
  - Classes: classes.md
  - Functions: functions.md
  - Descriptions: descriptions.md
theme:
  name: material
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
  - def_list
  - attr_list
  - md_in_html
  - smarty
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.betterem
  - pymdownx.critic