site_name: idkROM Documentation

nav:
  - Home: index.md
  - Description: descriptions.md
  - How to: main.md
  - Preprocessing: 
      - Data divider: pre/csv_div.md
      - Data loader: pre/loader.md
      - General preprocessing: pre/preprocessing.md
      - Sklearn toolbox: pre/sklearn_pre.md
  - Postprocessing: 
      - Save model: utils/save_model.md
      - Metrics: utils/metrics.md
  - Architectures:
      - Neural Network: architectures/neural_network.md
      - Gaussian process: architectures/gaussian_process.md
      - SVR: architectures/svr.md

theme:
  name: material

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: ["../src"]
          options:
            show_private_members: true
            filters: []  # <--- ¡Esto permite mostrar TODO sin filtrar!

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
  - def_list
  - attr_list
  - md_in_html
  - smarty
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.betterem
  - pymdownx.critic
